# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# Site header
header:
  navbar:
    enable: true
    blox: floating-theme-toggler

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
